### ISSUE TITLE
Testing GitHub Sponsors

### ISSUE THREAD

**Issue by extratone** [extratone/bilge#113]
# Testing GitHub Sponsors

![Testing GitHub Sponsors](https://user-images.githubusercontent.com/43663476/116671682-d6c62400-a966-11eb-8ae0-e6d68799904c.png)

## Introduction

G̏̽͋ͩͬ͊̈́o͌ͭ͆̂̍̈́̌oͩ͒ͩd̋̃͑ ͐ͣm̌orͬͥͤͣ̊n̋ͧͩ͐i͛̉n̔̎g̏͂̔ͦ̈!̿̍͆̽͒̍

I'm David Blue and **I am not a software developer**. Though I do fairly regularly author and distribute various tool-adjacent configurations you may find of value, I am fundamentally *not a builder*, though I am relentlessly compelled to seek out spaces like GitHub where builders congregate around the context of work 

***

* "[Setting up GitHub Sponsors for your user account](https://docs.github.com/en/sponsors/receiving-sponsorships-through-github-sponsors/setting-up-github-sponsors-for-your-user-account)"
* [Jeremy Keith's example profile](https://github.com/sponsors/adactio)

```
Don’t forget to delete this placeholder text 🙃

Here are some ideas of what you can tell your potential sponsors:
- [ ] Who are you, and where are you from?
- [ ] What are you working on?
- [ ] Why is their sponsorship important? How will you use the funds?

Hint: You can include images and emojis in your bio!
```

**Comment by extratone** [comment]
# Embeddables
**Button**

`<iframe src="https://github.com/sponsors/extratone/button" title="Sponsor extratone" height="35" width="116" style="border: 0;"></iframe>`

**Card**
`<iframe src="https://github.com/sponsors/extratone/card" title="Sponsor extratone" height="225" width="600" style="border: 0;"></iframe>`
